spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: trace
    com.zaxxer.hikari: debug

jwt:
  secret: socket-secret-key-for-local-please

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"