spring:
  datasource:
    url: ${datasource.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  lifecycle:
    timeout-per-shutdown-phase: 60s

logging:
  level:
    org.springframework.security: trace

server:
  shutdown: graceful
  forward-headers-strategy: native

jwt:
  secret: ${JWT.KEY}