spring:
  profiles:
    group:
      local:
        - flyway
        - localdb
        - local-security
        - local-cors
      prod:
        - flyway
        - prod-cors
        - prod-security
      test:
        - flyway
    active: local