spring:
  datasource:
    url: ${datasource.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  lifecycle:
    timeout-per-shutdown-phase: 60s
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging:
  level:
    org.springframework.security: info
    com.zaxxer.hikari: debug

server:
  shutdown: graceful
  forward-headers-strategy: native

jwt:
  secret: ${JWT.KEY}

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"