spring:
  datasource:
    url: ${datasource.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      format_sql: true
      ddl-auto: validate
    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace